services:
  - type: web
    name: xs-scraper-api
    env: node
    plan: starter
    buildCommand: npm ci --only=production
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: MONGODB_URI
        sync: false
      - key: REDIS_URL
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: SCRAPE_SCHEDULE
        value: "14 18 * * *"
      - key: SCRAPE_SCHEDULE_MT
        value: "14 17 * * *"
      - key: SCRAPE_SCHEDULE_MN
        value: "12 16 * * *"
      - key: TIMEZONE
        value: Asia/Ho_Chi_Minh
      - key: SCRAPER_RETRY_ATTEMPTS
        value: "3"
      - key: SCRAPER_RETRY_DELAY
        value: "5000"
      - key: LOG_LEVEL
        value: info
    healthCheckPath: /api/scraper/status
    autoDeploy: true
    region: oregon
    scaling:
      minInstances: 1
      maxInstances: 1 